import property1 from '../assets/images/4-mini.png';
import property2 from '../assets/images/4-mini.png';

import { features } from './apartments_detail/features';
import { description } from './apartments_detail/description';
import { images } from './apartments_detail/images';

export const apartments_data = [
  {
    id: 0,
    images: [property1, property2],
    name: 'Belem 21',
    price: 85,
    bedrooms: 1,
    bathrooms: 1,
    size: 107,
    description: description[0],
    features: features[0],
    address: 'Rua Alfredo da Silva, 3D 1300040 Ajuda, Lisbon',
  },
  {
    id: 1,
    images: images['Bica do Marques 15'],
    name: 'Bica do Marques 15',
    price: 75,
    bedrooms: 1,
    bathrooms: 1,
    size: 51,
    description: description[1],
    features: features[1],
    address: 'Rua Alfredo da Silva, 3D 1300040 Ajuda, Lisbon',
  },
  {
    id: 2,
    images: [property1, property2],
    name: 'Memoria 25',
    price: 95,
    bedrooms: 2,
    bathrooms: 2,
    size: 58,
    description: description[2],
    features: features[2],
    address: 'Rua Alfredo da Silva, 3D 1300040 Ajuda, Lisbon',
  },
  {
    id: 3,
    images: [property1, property2],
    name: 'Principe Real 31',
    price: 75,
    bedrooms: 1,
    bathrooms: 1,
    size: 46,
    description: description[3],
    features: features[3],
    address: 'Rua Alfredo da Silva, 3D 1300040 Ajuda, Lisbon',
  },
  {
    id: 4,
    images: [property1, property2],
    name: 'Rodrigues Sampaio 28',
    price: 175,
    bedrooms: 2,
    bathrooms: 2,
    wc: 1,
    size: 118,
    levels: 2,
    description: description[4],
    features: features[4],
    address: 'Rua Alfredo da Silva, 3D 1300040 Ajuda, Lisbon',
  },
  {
    id: 5,
    images: [property1, property2],
    name: 'Sampaio 28',
    price: 145,
    bedrooms: 2,
    bathrooms: 2,
    elevator: 1,
    size: 88,
    description: description[5],
    features: features[5],
    address: 'Rua Alfredo da Silva, 3D 1300040 Ajuda, Lisbon',
  },
];
